name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Dispara o workflow quando há um push na branch 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Usa o ambiente Ubuntu mais recente para rodar os passos

    steps:
    - name: Checkout repository # Pega o código do seu repositório
      uses: actions/checkout@v4

    - name: Setup Node.js # Configura o ambiente Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Use a versão do Node.js que você está usando (20 é uma boa padrão)
        cache: 'npm' # Habilita o cache de dependências do npm para builds mais rápidos

    # --- INÍCIO DA NOVA CORREÇÃO: LIMPAR CACHE E REINSTALAR ---
    - name: Clear npm cache # Limpa o cache do npm para garantir uma instalação limpa
      run: npm cache clean --force

    - name: Install dependencies # Instala as dependências do seu projeto
      run: npm install --force # Usa --force para garantir que tudo seja reinstalado
    # --- FIM DA NOVA CORREÇÃO ---

    - name: Grant execute permissions to node_modules binaries # Damos permissão de execução a todos os binários na pasta .bin
      run: chmod -R +x node_modules/.bin/

    - name: Build React app # Constrói seu aplicativo React com Vite
      run: npm run build

    - name: Deploy to GitHub Pages # Implanta o aplicativo construído no GitHub Pages
      uses: peaceiris/actions-gh-pages@v3 # Action específica para GitHub Pages
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }} # Token de acesso fornecido automaticamente pelo GitHub
        publish_dir: ./dist # A pasta 'dist' é onde o Vite coloca os arquivos de build