name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Dispara o workflow quando há um push na branch 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Usa o ambiente Ubuntu mais recente para rodar os passos

    steps:
    - name: Checkout repository # Pega o código do seu repositório
      uses: actions/checkout@v4

    - name: Setup Node.js # Configura o ambiente Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Use a versão do Node.js que você está usando (20 é uma boa padrão)
        cache: 'npm' # Habilita o cache de dependências do npm para builds mais rápidos

    - name: Install dependencies # Instala as dependências do seu projeto
      run: npm install

    # --- INÍCIO DA CORREÇÃO PARA O ERRO 'EACCES' ---
    - name: Grant execute permissions to esbuild # Damos permissão de execução ao binário do esbuild
      run: chmod +x node_modules/@esbuild/linux-x64/bin/esbuild
    # --- FIM DA CORREÇÃO ---

    - name: Build React app # Constrói seu aplicativo React com Vite
      run: npm run build

    - name: Deploy to GitHub Pages # Implanta o aplicativo construído no GitHub Pages
      uses: peaceiris/actions-gh-pages@v3 # Action específica para GitHub Pages
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }} # Token de acesso fornecido automaticamente pelo GitHub
        publish_dir: ./dist # A pasta 'dist' é onde o Vite coloca os arquivos de build