name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Clear npm cache and force install dependencies
      run: |
        npm cache clean --force
        npm install --force

    - name: Grant execute permissions to node_modules binaries
      run: chmod -R +x node_modules/.bin/

    - name: Grant execute permissions to esbuild binary
      run: chmod +x node_modules/@esbuild/linux-x64/bin/esbuild

    # --- PASSOS DE DIAGNÓSTICO (MANTIDOS POR ENQUANTO) ---
    - name: Diagnose permissions AFTER all chmod commands
      run: |
        echo "Permissions for esbuild AFTER all chmod commands:"
        ls -la node_modules/@esbuild/linux-x64/bin/esbuild || true
        echo "Permissions for vite binary AFTER all chmod commands:"
        ls -la node_modules/.bin/vite || true
        echo "Permissions for node_modules/.bin/ directory AFTER all chmod commands:"
        ls -la node_modules/.bin/ || true
    # --- FIM DOS PASSOS DE DIAGNÓSTICO ---

    - name: Build React app
      run: npm run build

    - name: Diagnose 'dist' directory content # NOVO PASSO DE DIAGNÓSTICO
      run: |
        echo "Content of dist directory:"
        ls -la dist/ || true # Lista o conteúdo da pasta dist

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist # Mantido, mas se der erro de cp, podemos tentar ${GITHUB_WORKSPACE}/dist