name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Dispara o workflow quando há um push na branch 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Usa o ambiente Ubuntu mais recente para rodar os passos

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Verifique se esta versão corresponde à sua local
        cache: 'npm'

    - name: Clear npm cache and force install dependencies
      run: | # O símbolo '|' permite múltiplos comandos
        npm cache clean --force
        npm install --force

    # --- INÍCIO DOS PASSOS DE DIAGNÓSTICO E CORREÇÃO ---
    - name: Diagnose permissions BEFORE chmod
      run: |
        echo "Permissions for esbuild before chmod:"
        ls -la node_modules/@esbuild/linux-x64/bin/esbuild || true
        echo "Permissions for vite binary before chmod:"
        ls -la node_modules/.bin/vite || true
        echo "Permissions for node_modules/.bin/ directory before chmod:"
        ls -la node_modules/.bin/ || true

    - name: Grant execute permissions to node_modules binaries
      run: chmod -R +x node_modules/.bin/

    - name: Diagnose permissions AFTER chmod
      run: |
        echo "Permissions for esbuild AFTER chmod:"
        ls -la node_modules/@esbuild/linux-x64/bin/esbuild || true
        echo "Permissions for vite binary AFTER chmod:"
        ls -la node_modules/.bin/vite || true
        echo "Permissions for node_modules/.bin/ directory AFTER chmod:"
        ls -la node_modules/.bin/ || true
    # --- FIM DOS PASSOS DE DIAGNÓSTICO E CORREÇÃO ---

    - name: Build React app
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist